# We have to use the node-modules linker as Yarn PnP does not always work properly
# See: https://github.com/vitejs/vite/issues/10802
# See: https://github.com/vitejs/vite/issues/15496
nodeLinker: node-modules
nmMode: hardlinks-global

# Enable dependency cooldowns for security reasons
npmMinimalAgeGate: 1w

# Allow using our temporary Parcel fork
approvedGitRepositories:
  - https://github.com/filips123/parcel.git
