# This is a recipe file for cargo-make <https://github.com/sagiegurari/cargo-make> used to manage the project

[config]
skip_core_tasks = true

### BUILDERS ###

[tasks.build]
description = "Build the project"
command = "cargo"
args = ["build", "--release"]

### INSTALLERS ###

[tasks.install.windows]
dependencies = ["build"]
install_script = [
    "heat >nul 2>nul || echo FATAL: Make sure the WiX Toolset is installed and available in the PATH environment variable && exit 1",
    "cargo-wix help >nul 2>nul || cargo install cargo-wix --git https://github.com/filips123/cargo-wix --rev 4448d466a45fe4210642d82ccb84ee9cdebd8ef7",
]
script = [
    "heat dir userchrome -o packages/wix/userchrome.wxs -scom -frag -srd -sreg -gg -cg UserChrome -var wix.UserChromeSource -dr UserChromeDir",
    "cargo wix --verbose --no-build --nocapture --install"
]

[tasks.install.linux]
dependencies = ["build"]
script = """
# Use sudo if it exists
SUDO=$(which sudo) || $(echo "")

# Copy all files to the correct locations
$SUDO install -D target/release/firefoxpwa /usr/bin/firefoxpwa
$SUDO install -D target/release/firefoxpwa-connector /usr/libexec/firefoxpwa-connector
$SUDO install -D manifests/linux.json /usr/lib/mozilla/native-messaging-hosts/firefoxpwa.json
$SUDO install -D manifests/linux.json /usr/lib64/mozilla/native-messaging-hosts/firefoxpwa.json

# Copy the userchrome directory to the correct location
$SUDO mkdir -p /usr/share/firefoxpwa/userchrome/
$SUDO cp -R userchrome/* /usr/share/firefoxpwa/userchrome/
"""

[tasks.install.mac]
dependencies = ["build"]
script = """
# Use sudo if it exists
SUDO=$(which sudo) || $(echo "")

# Copy all files to the correct locations
$SUDO install -d /usr/local/bin
$SUDO install -v target/release/firefoxpwa /usr/local/bin/firefoxpwa

$SUDO install -d /usr/local/libexec
$SUDO install -v target/release/firefoxpwa-connector /usr/local/libexec/firefoxpwa-connector

$SUDO install -d /Library/Application\\ Support/Mozilla/NativeMessagingHosts
$SUDO install -v manifests/macos.json /Library/Application\\ Support/Mozilla/NativeMessagingHosts/firefoxpwa.json

# Copy the userchrome directory to the correct location
$SUDO mkdir -p /usr/local/share/firefoxpwa/userchrome/
$SUDO cp -R userchrome/* /usr/local/share/firefoxpwa/userchrome/
"""

[tasks.install]
description = "Install the project"
script = [
    "echo FATAL: This environment does not support automatic installation using cargo-make",
    "exit 1"
]
