name: Docs CI/CD

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

defaults:
  run:
    working-directory: docs
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configure cache
        run: echo "CACHE_ID=$(date --utc '+%Y-%V')" >> $GITHUB_ENV

      - name: Configure cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ./docs/.cache
          key: mkdocs-${{ env.CACHE_ID }}
          restore-keys: mkdocs-

      - name: Install Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'
          cache: pip

      - name: Install Wrangler
        run: npm install -g wrangler@4.x

      - name: Install pngquant
        run: sudo apt-get update && sudo apt-get install -y pngquant

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the documentation
        run: mkdocs build

      - name: Publish the documentation
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=pwasforfirefox --branch=main
          workingDirectory: docs
