name: Docs CI/CD

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

defaults:
  run:
    working-directory: docs
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Configure cache
        run: echo "CACHE_ID=$(date --utc '+%Y-%V')" >> $GITHUB_ENV

      - name: Configure cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ./docs/.cache
          key: mkdocs-${{ env.CACHE_ID }}
          restore-keys: mkdocs-

      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
          cache: pip

      - name: Install Wrangler
        run: npm install -g wrangler@4.x

      - name: Install pngquant
        run: sudo apt-get update && sudo apt-get install -y pngquant

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the documentation
        run: mkdocs build

      - name: Publish the documentation
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=pwasforfirefox --branch=main
          workingDirectory: docs
