name: Extension CI/CD

on:
  push:
    paths:
      - .github/workflows/extension.yaml
      - extension/**
    tags:
      - v*
    branches-ignore:
      - crowdin-*
  pull_request:
    paths:
      - .github/workflows/extension.yaml
      - extension/**

defaults:
  run:
    working-directory: extension
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Configure cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/yarn
            ~/.config/yarn
            ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-lint-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint the extension
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Harden runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Configure cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/yarn
            ~/.config/yarn
            ~/.yarn/berry/cache
          key: ${{ runner.os }}-yarn-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Set the version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]
          then
            VERSION=${GITHUB_REF/refs\/tags\/v}
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            sed -i "s/\"version\": \"0.0.0\"/\"version\": \"$VERSION\"/g" package.json
            sed -i "s/\"version\": \"0.0.0\"/\"version\": \"$VERSION\"/g" src/manifest.json
          else
            echo "VERSION=0.0.0" >> $GITHUB_ENV
          fi

      - name: Package the extension source
        run: 7z a "dist/firefoxpwa-${{ env.VERSION }}-source.zip" "." -bd  -mx9 -xr@"../.gitignore"

      - name: Upload the extension source
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: firefoxpwa-extension-source
          path: extension/dist/firefoxpwa-*-source.zip
          archive: false

      - name: Attest the extension source
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: extension/dist/firefoxpwa-*-source.zip

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build the extension
        run: yarn build

      - name: Upload the compiled extension
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: firefoxpwa-extension-compiled
          path: extension/dist/firefoxpwa-*-compiled.zip
          archive: false

      - name: Attest the compiled extension
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: extension/dist/firefoxpwa-*-compiled.zip

  # Add auto-publishing to AMO once web-ext supports submitting extensions from ZIP files
  # This also includes uploading source code and AMO release notes
  # See: https://github.com/mozilla/web-ext/issues/3242
